name: pr-merge - update production

on:
  pull_request:
    types: [closed]
env:
  IMAGE_NAME: yp3yp3/weather
  CD_REPO: yp3yp3/weather-CD 
  USER_NAME: yp3yp3
  EMAIL: yp3yp3@gmail.com
jobs:

  update-production-on-main-change:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        name: Update production deployment in CD repo
        with:
          repository: ${{ env.CD_REPO }}
          token: ${{ secrets.GIT_PASSWORD }}

      - name: Update production environment with new image
        run: |
          git config --global user.name "${{ env.USER_NAME }}"
          git config --global user.email "${{ env.EMAIL }}"
          VERSION=$(grep 'tag:' values-stage.yaml | awk '{print $2}')    
          sed -i "s|tag:.*\$|tag: $VERSION|g" values-prod.yaml
          cat values-prod.yaml
          git add -A
          git commit -m "Update Production environment to image version $VERSION"
          git push             
